name: Pipeline workflow

on:
  push:
    branches:
      - main
      - feature/**
    
  pull_request:
    branches:
      - main


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Copy the repo into VM
        uses: actions/checkout@v4

      - name: Install Node into VM
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Compile typescript
        run: npx tsc --noEmit

      - name: Test 
        run: npm test